### ISSUE TITLE
Analysis completed without output

### ISSUE THREAD

**Issue by rtpwilliams** [moore-andrew05/FIJI_ImageStitcher9000#6]
Summary of issue: 
The analysis completed without any output. Additionally, the code completed instantaniosuly, ie `Time Elapsed: 0 mins, 0 secs`

Analysis paramters:
`Enter Image Directory: /Volumes/WormHole/robert/220711_ELT-2_Regulation_Rep2/ELT2gfp/ELT2rnai
Enter output directory (Stitched images will be saved here): /Users/rtpw/Documents/FrankenStein/Rep2/ELT2gfp/ELT2rnai
Enter the name of the images (do not include incrementors): 220711_ELT2gfp_ELT2rnai_worm
Would you like to proceed to Stitching full z-stacks?: yes
If stitching full z-stacks, type (y)es to MAX project and save: y
Would you like to also save the full stitched image with z-stacks?: y`

**Comment by moore-andrew05** [comment]
Due to me not releasing new version that can handle incrementors with or without leading zeroes. New release (v0.1.0) should solve this.
